# Generated by Django 2.2.4 on 2021-03-30 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo_app', '0002_styles_style_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='books_open',
            new_name='availability',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='website',
        ),
        migrations.AddField(
            model_name='profile',
            name='deposit',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(max_length=45)),
                ('contact_name', models.CharField(max_length=200)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='tattoo_app.Profile')),
            ],
        ),
    ]
