# Generated by Django 2.2.4 on 2021-03-31 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo_app', '0004_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location_map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_location_map', to='tattoo_app.Map'),
        ),
    ]
