# Generated by Django 2.2.4 on 2021-04-01 13:51

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo_app', '0005_profile_location_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location_map',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=mapbox_location_field.models.AddressAutoHiddenField(default='Dallas, Texas, United States', map_id='map'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': (-96.7969, 32.7763), 'style': 'mapbox://styles/mightysharky/cjwgnjzr004bu1dnpw8kzxa72'}),
        ),
    ]
